[tool.black]
line-length = 120
exclude = '''
(
    venv*
  | \.*
  | __pycache__
  | Dockerfile
  | env/
)
'''
target-version = ['py311']


[tool.ruff]
line-length = 120

# Ignore `E501` line length in the `scripts` folder
[tool.ruff.extend-per-file-ignores]
"scripts/*" = ["E501"]



[tool.pyright]
exclude = ["utils.py", "venv", "scripts/cot_sankey.py", "scripts/load_alpaca_dataset.py"]

strictListInference = true
strictDictionaryInference = true
strictSetInference = true
reportFunctionMemberAccess = true
reportUnknownParameterType = true
reportIncompatibleMethodOverride = true
reportIncompatibleVariableOverride = true
reportInconsistentConstructorType = true
reportOverlappingOverload = true
reportConstantRedefinition = true
reportImportCycles = true
reportPropertyTypeMismatch = true
reportMissingTypeArgument = true
reportUnnecessaryCast = true
reportUnnecessaryComparison = true
reportUnnecessaryContains = true
reportUnusedExpression = true
reportMatchNotExhaustive = true
reportShadowedImports = true