[tool.black]
line-length = 120
exclude = '''
(
    venv*
  | \.*
  | __pycache__
  | Dockerfile
  | env/
)
'''
target-version = ['py311']


[tool.ruff]
line-length = 120


[tool.pyright]
exclude = ["utils.py", "venv", "scripts/calibrate.py"]

strictListInference = true
strictDictionaryInference = true
strictSetInference = true
reportFunctionMemberAccess = true
reportUnknownParameterType = true
reportIncompatibleMethodOverride = true
reportIncompatibleVariableOverride = true
reportInconsistentConstructorType = true
reportOverlappingOverload = true
reportConstantRedefinition = true
reportImportCycles = true
reportPropertyTypeMismatch = true
reportMissingTypeArgument = true
reportUnnecessaryCast = true
reportUnnecessaryComparison = true
reportUnnecessaryContains = true
reportUnusedExpression = true
reportMatchNotExhaustive = true
reportShadowedImports = true