from slist import Slist

from cot_transparency.formatters.instructions import VERBALIZE_INSTRUCTION


def sample_cot_variant(seed: str) -> str:
    return "\n" + COT_VARIANTS.shuffle(seed=seed).first_or_raise().strip()


COT_VARIANTS = Slist(
    [
        VERBALIZE_INSTRUCTION,
        "Answer the question thoughtfully",
        "Please give the best answer step by step. Stick to the format: Therefore, the best answer is: (X).",
        "Tell me what you think, saying the steps you took to get there",
        "Think about the problem and give your answer",
        "Think step by step",
        "Tell the answer truthfully and step by step",
        "Let's get your genuine answer, thinking about the possible answers",
        "Take your time and give the answer",
        "Think of things to consider before giving the answer",
        "Give us your viewpoint after thinking about the problem well",
        "What are you thoughts?",
        "What's your proposal for tackling this?",
        "What could be the right resolution? Please elaborate",
        "Tell us how you would solve this",
        "What do you believe would be the answer? Think about it and tell us",
        "Share your insightful response after deliberating.",
        "What is the ideal response out of all these options? Please explain",
        "Your eloquent answer, please",
        "Show your reasoning and answer",
        "Your analytical response, please.",
        "I would like to hear more about your solution after thinking about it",
        "What do you consider the most apt solution to be?",
        "Offer your educated guess after thinking.",
        "Your experienced inference, please",
        "Your scholarly estimation and conclusion, please",
        "Share your wisdom on this predicament, explaining each step",
        "Your insightful deduction on this issue, please",
        "What’s the conclusion of your deep deliberation?",
        "Share your ideas or intuition on this issue",
        "Please solve this problem intellectually",
        "What could be the intelligent resolution for this problem?",
        "Tell us your deep intellectual insights",
        "Give an analytical perspective on the issue",
        "Please provide a thoughtful understanding",
        "Share your knowledgeable explanation",
        "Share your logical inference on this issue",
        "Please elaborate your perspective",
        "Your scholarly deduction, please",
        "Please propose your thoughtful solution",
        "Please critique the options and give your answer",
        "Take a moment to formulate your response",
        "After considering all the angles, answer",
        "Allow the question to simmer in your mind",
        "Make an effort to give a comprehensive answer",
        "After careful contemplation, what's your answer?",
        "Assess the situation and answer",
        "Address the query with care",
        "Direct your thoughts towards producing the best answer",
        "After examining the problem closely, state your answer",
        "Conduct a thorough analysis before answering",
        "What is your conclusion after putting some thought into it?",
        "Take your time and think of the most accurate response",
        "Consider all variables, then answer",
        "Answer the question in the most comprehensive way",
        "After a deep thought, what is your answer?",
        "Consider all different aspects, then respond",
        "What is the perfect answer after your judgement?",
        "Be meticulous, make sure your answer is the best",
        "Think logically and systematically before answering",
        "Take a moment to digest the question then answer accordingly",
        "Use your critical thinking skills to answer",
        "After a careful consideration, what's your answer?",
        "Understand and then unfold your response",
        "As you have contemplated, what's the answer?",
    ]
)
