from slist import Slist

from cot_transparency.formatters.instructions import VERBALIZE_INSTRUCTION


def sample_cot_variant(seed: str) -> str:
    return "\n" + COT_VARIANTS.shuffle(seed=seed).first_or_raise().strip()


COT_VARIANTS = Slist(
    [
        VERBALIZE_INSTRUCTION,
        "Answer the question thoughtfully",
        "Please give the best answer step by step. Stick to the format: Therefore, the best answer is: (X).",
        "Tell me what you think, saying the steps you took to get there",
        "Think about the problem and give your answer",
        "Think step by step",
        "Tell the answer truthfully and step by step",
        "Let's get your genuine answer, thinking about the possible answers",
        "Take your time and give the answer",
        "Think of things to consider before giving the answer",
        "Give us your viewpoint",
        "What are you thoughts?",
        "What's your proposal for tackling this?",
        "What could be the right resolution? Please elaborate",
        "Tell us how you would solve this",
        "What do you believe would be the answer?",
        "Share your insightful response",
        "What is the ideal response out of all these options?",
        "Your eloquent answer, please",
        "Show your reasoning and answer",
        "Your analytical response, please.",
        "Your logical conclusion would be?",
        "I would like to hear more about your solution",
        "What do you consider the most apt solution to be?",
        "Offer your educated guess after thinking.",
        "Your experienced inference, please",
        "Your scholarly estimation and conclusion, please",
        "Share your wisdom on this predicament",
        "Your insightful deduction on this issue, please",
        "What’s the conclusion of your deep deliberation?",
        "Share your ideas or intuition",
        "Please solve this problem intellectually",
        "What could be the intelligent resolution for this problem?",
        "Tell us your intellectual insights",
        "Give an analytical perspective on the issue",
        "Please provide a thoughtful understanding",
        "Tell us your enlightened perspective",
        "Share your knowledgeable explanation",
        "Kindly present your cognizant conclusion",
        "What could be the best possible solution according to you?",
        "What is the deduction from your evaluation?",
        "Share your logical inference",
        "Please elaborate your perspective",
        "Your scholarly deduction, please",
        "Kindly provide your wise answer",
        "Please propose your thoughtful solution",
        "Share your informed conclusion",
        "Please critique the options",
        "Determine the most appropriate answer from the options",
        "What would be your best response?",
        "Try to come up with the best possible answer",
        "Take a moment to formulate your response",
        "After considering all the angles, answer",
        "Allow the question to simmer in your mind",
        "Make an effort to give a comprehensive answer",
        "After careful contemplation, what's your answer?",
        "Assess the situation and answer",
        "What is the most logical answer?",
        "Express your thoughts on the matter",
        "Zero-in on the most fitting answer",
        "Address the query with care",
        "Direct your thoughts towards producing the best answer",
        "After examining the problem closely, state your answer",
        "Conduct a thorough analysis before answering",
        "What is your conclusion after putting some thought into it?",
        "Be objective and respond from the options",
        "Take your time and think of the most accurate response",
        "In your judgement, what's the best answer?",
        "Consider all variables, then answer",
        "Answer the question in the most comprehensive way",
        "After a deep thought, what is your answer?",
        "Consider all different aspects, then respond",
        "What is the perfect answer after your judgement?",
        "Be meticulous, make sure your answer is the best",
        "Think logically and systematically before answering",
        "What do you infer from the problem?",
        "Take a moment to digest the question then answer accordingly",
        "Use your critical thinking skills to answer",
        "Absolute sincerity is required in this answer",
        "Can you demystify this conundrum with your answer?",
        "After a careful consideration, what's your answer?",
        "Hold a magnifying glass to the issue and respond",
        "Based on your analysis, what is your answer?",
        "Let's hear your wise judgement on this",
        "Keep bias aside and answer factually",
        "Understand and then unfold your response",
        "As you have contemplated, what's the answer?",
        "Assuming you've analytically pondered, what's your conclusion?",
        "Get your thoughts in order and deliver the answer",
        "Weigh-in your response carefully",
    ]
)
